@startuml
class App {
    +void main()
}

class product{
    +name : String
    +price : double
    +quantity : int
}

class productInventory {
    +products: product
    +String inventorySearch(String prodName)
}

App *- productInventory
App *- product
@enduml